const TRANSVERSAL_KEYTERMS = [
  "anecoico",
  "hipoecoico",
  "hiperecoico",
  "isoecoico",
  "ecotextura",
  "ecogenicidade",
  "ecográfico",
  "sombra acústica",
  "Doppler colorido",
  "transdutor",
  "córtico-medular",
  "parênquima",
] as const;

const OBSTETRIC_KEYTERMS = [
  "Hadlock",
  "Intergrowth",
  "Gratacós",
  "BI-RADS",
  "TI-RADS",
  "O-RADS",
  "FIGO",
  "oligoâmnio",
  "polidrâmnio",
  "incisura",
  "ducto venoso",
  "artéria cerebral média",
  "translucência nucal",
  "pré-centralização",
  "leiomioma",
  "adenomiose",
  "endometrioma",
  "cisterna magna",
  "osso nasal",
  "amniótico",
  "biometria",
  "cefálico",
  "placenta",
  "Grannum",
] as const;

const SPECIALTY_KEYTERMS = {
  msk: [
    "bursa",
    "subacromial",
    "subdeltóidea",
    "tendinopatia",
    "tendíneo",
    "supraespinal",
    "supraespinhoso",
    "infraespinal",
    "subescapular",
    "cabo longo do bíceps",
    "calcária",
    "entesófito",
    "bursite",
    "derrame articular",
    "cisto de Baker",
    "rotura",
    "fibrilar",
    "fáscia plantar",
    "epicondilite",
    "líquido sinovial",
  ],
  vascular: [
    "pampiniforme",
    "safena magna",
    "safena parva",
    "perfurante",
    "refluxo",
    "recanalização",
    "incompetência",
    "trombose",
    "poplítea",
    "femoral",
    "tibial",
    "fibular",
    "panturrilha",
    "carótida",
    "vertebral",
    "bulbo carotídeo",
    "médio-intimal",
    "anterógrado",
    "retrógrado",
    "fístula arteriovenosa",
    "anastomose",
  ],
  abdomen: [
    "colédoco",
    "hepatopatia",
    "esteatose",
    "colelitíase",
    "nefrolitíase",
    "pielocalicial",
    "seio renal",
    "ateromatose",
    "cálculo",
    "microlitíase",
    "cortical",
    "hilar",
    "esplênico",
    "pancreático",
  ],
  escrotal: [
    "epidídimo",
    "varicocele",
    "hidrocele",
    "microlitíase",
    "Valsalva",
    "testicular",
  ],
  tireoideMama: [
    "TI-RADS",
    "BI-RADS",
    "O-RADS",
    "istmo",
    "tireoidite",
    "Hashimoto",
    "fibroadenoma",
    "linfonodo",
    "retroareolar",
    "Robbins",
    "parótida",
    "submandibular",
  ],
  classificacoes: [
    "BI-RADS",
    "TI-RADS",
    "O-RADS",
    "PI-RADS",
    "FIGO",
    "Bosniak",
    "NASCET",
    "Sarteschi",
    "Papile",
  ],
} as const;

const CATEGORY_GROUPS: Record<string, readonly (keyof typeof SPECIALTY_KEYTERMS)[]> = {
  MUSCULOESQUELETICO: ["msk"],
  MUSCULOESQUELETICO_V2: ["msk"],
  MUSCULOESQUELETICO_RARAS: ["msk"],
  PARTES_MOLES: ["msk"],
  DOPPLER_CAROTIDAS: ["vascular"],
  DOPPLER_VENOSO_MMII: ["vascular"],
  DOPPLER_VENOSO_MMII_MEDIDAS: ["vascular"],
  DOPPLER_ARTERIAL_MMII: ["vascular"],
  DOPPLER_FISTULA_AV: ["vascular"],
  DOPPLER_RENAL: ["vascular", "abdomen"],
  DOPPLER_VENOSO_MMSS: ["vascular"],
  DOPPLER_ARTERIAL_MMSS: ["vascular"],
  ABDOMEN_TOTAL: ["abdomen"],
  ABDOMEN_TOTAL_DOPPLER: ["abdomen", "vascular"],
  ABDOMEN_SUPERIOR: ["abdomen"],
  VIAS_URINARIAS: ["abdomen"],
  ESCROTAL: ["escrotal", "vascular"],
  TIREOIDE: ["tireoideMama"],
  PARATIREOIDE: ["tireoideMama"],
  CERVICAL: ["tireoideMama"],
  GLANDULAS_SALIVARES: ["tireoideMama"],
  MAMARIA: ["tireoideMama"],
};

function unique(terms: readonly string[]): string[] {
  return [...new Set(terms)];
}

export const ALL_MEDICAL_ASR_KEYTERMS = unique([
  ...TRANSVERSAL_KEYTERMS,
  ...OBSTETRIC_KEYTERMS,
  ...Object.values(SPECIALTY_KEYTERMS).flat(),
]);

export function medicalAsrKeytermsForCategory(category: string | null): string[] {
  const normalized = category?.trim().toUpperCase();
  if (!normalized) return ALL_MEDICAL_ASR_KEYTERMS;

  const groups = CATEGORY_GROUPS[normalized];
  if (!groups) return ALL_MEDICAL_ASR_KEYTERMS;

  return unique([
    ...TRANSVERSAL_KEYTERMS,
    ...OBSTETRIC_KEYTERMS,
    ...groups.flatMap((group) => SPECIALTY_KEYTERMS[group]),
    ...SPECIALTY_KEYTERMS.classificacoes,
  ]);
}
