/**
 * Few-shots do MSK writer_guarded — laudos REAIS assinados pelo Dr. Luiz (final_output).
 * O "estilo da casa" de verdade (técnica, agrupamento, linha em branco entre achados,
 * "X ecograficamente normal", termos do médico). Ensinar por EXEMPLO > regra.
 * Casos: 7c391290, aecad190, edcfee95, 0d36e3f4, 4c621d97, b98d2b06 (mão/punho, ombro-tend, tornozelo, ombro-deg, joelho, pé).
 * Curado 2026-07-02. NÃO editar à mão (regenerar do final_output).
 */
export const MSK_FEWSHOTS: ReadonlyArray<{ raw: string; laudo: string }> = [
  {
    "raw": "Do da mão direita, da mão esquerda, do punho direito e do punho esquerdo, no punho esquerdo, terinopatia tenossinovite do 4º compartimento extensor, Área de secção transversa do nervo mediano esquerdo normal, medindo 4 milímetros quadrados, No 3º quirodácto pode colocar mão esquerda, quer dizer 3º quirodácto da mão esquerda, imagem anecoica, com margem regular medindo 0.3 por 0.1 por 0.4 centímetros. No, Na conclusão com com cisto sinovial, ou comumente relacionado a a, entre parênteses dedo em gatilho, entre aspas, no e dedo em gatilho, Mão direita com rizartrose, punho direito Área de secção transversa do nervo mediano normal, medindo 5.1 milímetros quadrados na entrada do túnel do carpo,",
    "laudo": "ULTRASSONOGRAFIA DA MÃO DIREITA\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação da mão direita.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nArticulação trapézio-metacarpal do polegar direito apresentando irregularidade cortical marginal e osteófitos, compatível com alterações degenerativas.\n\nNão há sinais de derrame articular significativo ou coleções líquidas organizadas nos segmentos avaliados.\n\nCONCLUSÃO:\nRizartrose à direita.\n\n\n\nULTRASSONOGRAFIA DA MÃO ESQUERDA\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação da mão esquerda.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nImagem anecoica na polia A1, com margem regular, medindo aproximadamente 0,3 x 0,1 x 0,4 cm., situada no 3º quirodáctilo da mão esquerda.\n\nNão há sinais de coleções líquidas organizadas nos demais segmentos avaliados.\n\nCONCLUSÃO:\nImagem anecoica na polia A1 do 3º quirodáctilo da mão esquerda. O diagnóstico mais provável é cisto sinovial, achado comumente relacionado à tenossinovite estenosante (“dedo em gatilho”).\n\n\n\nULTRASSONOGRAFIA DO PUNHO DIREITO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação do punho direito.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nCompartimentos dos tendões extensores de aspecto habitual, sem tendinopatias ou tenossinovites.\n\nNa região volar do punho, o retináculo dos flexores apresenta padrão ecotextural normal. O nervo mediano não apresenta sinais de compressão.\n\nNervo mediano com área de secção transversa normal na entrada do túnel do carpo, medindo 5,1 mm².\n\nNão foram caracterizadas lesões expansivas ou variações anatômicas no interior do túnel do carpo.\n\nAusência de derrame articular ou hipertrofia sinovial nos recessos articulares do punho.\n\nCONCLUSÃO:\nPunho direito ecograficamente normal.\n\n\nULTRASSONOGRAFIA DO PUNHO ESQUERDO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação do punho esquerdo.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nTendões do 4º compartimento extensor, correspondendo aos tendões extensor comum dos dedos e extensor próprio do indicador, apresentando modificação do padrão ecotextural, associada a sinais de tenossinovite.\n\nNa região volar do punho, o retináculo dos flexores apresenta padrão ecotextural normal. O nervo mediano não apresenta sinais de compressão.\n\nNervo mediano esquerdo com área de secção transversa normal na entrada do túnel do carpo, medindo 4,0 mm².\n\nNão foram caracterizadas lesões expansivas ou variações anatômicas no interior do túnel do carpo.\n\nAusência de derrame articular significativo nos recessos articulares do punho.\n\nCONCLUSÃO:\nTendinopatia/tenossinovite dos tendões do 4º compartimento extensor do punho esquerdo."
  },
  {
    "raw": "Ultrassonografia do ombro direito com tendinopatia do supra infra e subescapular, com espessamento da bursa subafromial e subdeltoidea, no ombro esquerdo a mesma coisa.",
    "laudo": "ULTRASSONOGRAFIA DO OMBRO DIREITO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação do ombro direito.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nTendões supraespinhal, infraespinhal e subescapular com modificação do padrão ecotextural, sem evidência de roturas.\n\nTendão da cabeça longa do bíceps tópico, com espessura e ecotextura preservadas.\n\nEspessamento da bursa subacromial-subdeltoidea.\n\nCONCLUSÃO:\n1. Tendinopatia dos tendões supraespinhal, infraespinhal e subescapular do ombro direito.\n2. Bursite subacromial-subdeltoidea à direita.\n\n\n\nULTRASSONOGRAFIA DO OMBRO ESQUERDO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação do ombro esquerdo.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nTendões supraespinhal, infraespinhal e subescapular com modificação do padrão ecotextural, sem evidência de roturas.\n\nTendão da cabeça longa do bíceps tópico, com espessura e ecotextura preservadas.\n\nEspessamento da bursa subacromial-subdeltoidea.\n\nCONCLUSÃO:\n1. Tendinopatia dos tendões supraespinhal, infraespinhal e subescapular do ombro esquerdo.\n2. Bursite subacromial-subdeltoidea à esquerda."
  },
  {
    "raw": "Tornozelo direito\nTornozelo direito com irregularidade cortical, na inserção do, tendão do calcâneo, osteófitos não é, marginais, na conclusão do tendao de aquiles",
    "laudo": "ULTRASSONOGRAFIA DO TORNOZELO DIREITO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência 12 MHz. Foram realizados múltiplos cortes longitudinais e transversais do segmento avaliado. Avaliação dinâmica quando aplicável. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nAusência de derrame articular.\n\nTendão calcâneo com espessura preservada, sem evidência de roturas, apresentando irregularidade cortical na inserção distal do tendão calcâneo, associada a osteófitos/entesófitos marginais.\n\nTendões tibial anterior, tibial posterior, fibulares, extensores e flexores longo dos dedos e do hálux de espessura, continuidade e ecotextura preservadas.\n\nRecesso articular tibiotalar sem coleções ou derrame.\n\nCONCLUSÃO:\nTendinopatia insercional do tendão calcâneo direito."
  },
  {
    "raw": "Grafia do ombro esquerdo com alterações degenerativas da esquerda, com osteóficos marginais e regularidade cortical, E0E0 restante normal.",
    "laudo": "ULTRASSONOGRAFIA DO OMBRO ESQUERDO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência 12 MHz. Foram realizados múltiplos cortes longitudinais e transversais do segmento avaliado. Avaliação dinâmica quando aplicável. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nTendão supraespinhal de espessura, continuidade e ecotextura preservadas.\nTendão infraespinhal de espessura, continuidade e ecotextura preservadas.\nTendão subescapular de espessura, continuidade e ecotextura preservadas.\nCabo longo do bíceps tópico, de espessura e ecotextura preservadas.\nBursa subacromial-subdeltoidea sem distensão.\nAlterações degenerativas da articulação acromioclavicular esquerda, com osteóficos marginais e irregularidade cortical\nNão há sinais de derrame articular significativo.\n\nCONCLUSÃO:\nAlterações degenerativas da articulação acromioclavicular esquerda, com osteófitos marginais."
  },
  {
    "raw": "ULTRASSONOGRAFIA DO JOELHO DIREITO\n\nCOMENTÁRIOS:\n\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação do joelho direito.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\n\nTendões da pata de ganso com discreto espessamento e alteração ecotextural, sem sinais de rotura.\n\nNão há sinais de coleção líquida significativa na topografia da bursa anserina.\n\nTendão quadricipital e tendão patelar com espessura, continuidade e ecotextura preservadas.\n\nAusência de derrame articular significativo.\n\nPlanos subcutâneos avaliados sem alterações relevantes.\n\nCONCLUSÃO:\n\nTendinopatia dos tendões da pata de ganso do joelho direito.",
    "laudo": "ULTRASSONOGRAFIA DO JOELHO DIREITO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência, abrangendo a avaliação do joelho direito.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nTendões da pata de ganso com discreto espessamento e alteração ecotextural, sem sinais de rotura.\n\nNão há sinais de coleção líquida significativa na topografia da bursa anserina.\n\nTendão quadricipital e tendão patelar com espessura, continuidade e ecotextura preservadas.\n\nAusência de derrame articular significativo.\n\nPlanos subcutâneos avaliados sem alterações relevantes.\n\nCONCLUSÃO:\nTendinopatia dos tendões da pata de ganso do joelho direito."
  },
  {
    "raw": "Microcenografia do do pé esquerdo com do tendão tibial posterior, E ultrassonografia do punho direito normal, com área transversa do nervo mediano na entrada do túnel do carpo de 7 milímetros quadrados. também normal.",
    "laudo": "ULTRASSONOGRAFIA DO PÉ ESQUERDO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência 12 MHz. Foram realizados múltiplos cortes longitudinais e transversais do segmento avaliado. Avaliação dinâmica quando aplicável. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nFáscia plantar com espessura e ecotextura preservadas.\nTendão tibial posterior com modificação do padrão ecotextural, sem evidência de roturas.\nNão há sinais de coleções, lesões expansivas ou alterações ecográficas relevantes no segmento avaliado.\n\nCONCLUSÃO:\nTendinopatia do tendão tibial posterior esquerdo.\n\nULTRASSONOGRAFIA DO PUNHO DIREITO\n\nCOMENTÁRIOS:\nExame realizado com transdutor linear de alta frequência 12 MHz. Foram realizados múltiplos cortes longitudinais e transversais do segmento avaliado. Avaliação dinâmica quando aplicável. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nTendões flexores e retináculo dos flexores de aspecto preservado.\nCompartimentos extensores de aspecto preservado.\nNervo mediano de calibre e ecotextura preservados ao nível do túnel do carpo.\nNão há sinais de coleções, cistos sinoviais ou efusão articular no segmento avaliado.\n\nCONCLUSÃO:\nPunho direito ecograficamente normal."
  }
];
