/**
 * Few-shots do PELVE_FEMININA writer_guarded — laudos REAIS assinados pelo Dr. Luiz
 * (final_output). O "estilo da casa" da pelve por exemplo. Curado 2026-07-02.
 *
 * Cobertura: TA+TV normal + DIU (63a92f8e), TV + Naboth (df89063c), menopausa TA+TV
 * (2e4f1149), menopausa TA-only + ovário não-visualizado + arqueadas + obs-TA
 * (2f875727), mioma FIGO + O-RADS/anti-líquido-livre + istmocele (900c411c),
 * pós-abortamento/produtos retidos (2f132440).
 *
 * Normalização aplicada aos laudos (cosmética, documentada — a confirmar c/ Luiz):
 *  - medidas com VÍRGULA decimal (estilo do renderer LIVE = ptBr; os assinados
 *    variavam ponto/vírgula) — ex.: "5.4 x 2.0" → "5,4 x 2,0";
 *  - numeração da conclusão "1)" (alguns assinados usavam "1.").
 * Os raws foram limpos para DITADO NATURAL (removido bloco de instrução de menopausa
 * injetado pelo pipeline e ruído de ASR tipo "Legendas pela comunidade Amara.org").
 */
export const PELVE_FEWSHOTS: ReadonlyArray<{ raw: string; laudo: string }> = [
  // 1) TA+TV normal + DIU (imagem hiperecoica linear na cavidade).
  {
    raw: "Ultrassonografia da pelve transabdominal e transvaginal com útero em anteversão medindo 6,3 x 3,8 x 5,4 cm, com volume normal de 69,8. Adicione imagem hiperecoica linear, medindo 3,2 centímetros no seu maior eixo, distando 0,1 centímetros da extremidade superior à região fúndica. Endométrio mede 0,4, normal para fase do ciclo menstrual. Ovário direito medindo 2,0 x 1,9 x 2,1 cm, com volume de 4,4. Ovário esquerdo medindo 2,1 x 1,1 x 0,9, com volume de 1,1.",
    laudo:
      "ULTRASSONOGRAFIA DA PELVE TRANSABDOMINAL E TRANSVAGINAL\n\nCOMENTÁRIOS:\nExame realizado inicialmente com transdutor de 4.0 MHz, pela técnica transabdominal com a bexiga repleta e paciente em decúbito dorsal. Após a micção, foi introduzido transdutor de 6.5 MHz com a finalidade de realizar a técnica transvaginal. Foram realizados múltiplos cortes transversais, longitudinais, oblíquos e coronais, abrangendo toda a pelve. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nBexiga de forma, contorno e ecotextura normais.\nÚtero em anteversão, medindo 6,3 x 3,8 x 5,4 cm.\nEndométrio medindo 0,4 cm de espessura.\nImagem hiperecoica linear na cavidade endometrial, medindo 3,2 cm no seu maior eixo, distando 0,1 cm da extremidade superior à região fúndica.\nMiométrio com ecogenicidade e ecotextura normais.\nOvário direito medindo 2,0 x 1,9 x 2,1 cm, apresentando imagens anecoicas.\nOvário esquerdo medindo 2,1 x 1,1 x 0,9 cm, apresentando imagens anecoicas.\n\nCONCLUSÃO:\n1) Bexiga ecograficamente normal.\n2) Útero de volume normal (69,8 cm³).\n3) O endométrio tem espessura normal para a fase do ciclo menstrual.\n4) Ovários ecograficamente normais (o direito com 4,4 cm³ e o esquerdo 1,1 cm³), ambos contendo folículos.\n5) Dispositivo intrauterino (D.I.U.) normoposicionado.",
  },
  // 2) TV only + cistos de Naboth (colo).
  {
    raw: "Ultrassonografia da pelve transvaginal com útero em anteversão medindo 7,3 x 3,4 x 4,5 com volume de 60,5. Adicione também cisto de Naboth, ou seja, sequela de cervicite. Endométrio medindo 0,5 cm, espessura normal para a fase do ciclo menstrual. Ovário esquerdo medindo 1,5 x 1,3 x 1,3 com volume de 1,4, ovário direito medindo 1,1 x 1,1 x 1,2 com volume de 0,8.",
    laudo:
      "ULTRASSONOGRAFIA PÉLVICA TRANSVAGINAL\n\nCOMENTÁRIOS:\nExame realizado com transdutor de 6.5 MHz, pela técnica transvaginal. A documentação fotográfica foi obtida em 06 fotos, segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nÚtero em anteversão, medindo 7,3 x 3,4 x 4,5 cm.\nEndométrio medindo 0,5 cm de espessura.\nMiométrio com ecogenicidade e ecotextura normais.\nOvário direito medindo 1,1 x 1,1 x 1,2 cm, apresentando imagens anecoicas.\nOvário esquerdo medindo 1,5 x 1,3 x 1,3 cm, apresentando imagens anecoicas.\nImagens anecoicas na topografia do colo uterino.\n\nCONCLUSÃO:\n1) Útero de volume normal (60,5 cm³).\n2) O endométrio tem espessura normal para a fase do ciclo menstrual.\n3) Ovários ecograficamente normais (o direito com 0,8 cm³ e o esquerdo 1,4 cm³), ambos contendo folículos.\n4) Cistos de Naboth (provável sequela de cervicite).",
  },
  // 3) Menopausa TA+TV — ovários atróficos "poucas imagens anecoicas".
  {
    raw: "Ultrassonografia da pelve transabdominal e transvaginal com útero em anteversão, medindo 5,4 por 2,0 por 3,8 com volume de 22,3, endométrio medindo 0,2, ovário direito medindo 0,6 por 1,2 por 1,2 com volume de 0,4, ovário esquerdo medindo 1,2 por 0,9 por 1,0 com volume de 0,6. Paciente em menopausa.",
    laudo:
      "ULTRASSONOGRAFIA DA PELVE TRANSABDOMINAL E TRANSVAGINAL\n\nCOMENTÁRIOS:\nExame realizado inicialmente com transdutor de 4.0 MHz, pela técnica transabdominal com a bexiga repleta e paciente em decúbito dorsal. Após a micção, foi introduzido transdutor de 6.5 MHz com a finalidade de realizar a técnica transvaginal. Foram realizados múltiplos cortes transversais, longitudinais, oblíquos e coronais, abrangendo toda a pelve. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nBexiga de forma, contorno e ecotextura normais.\nÚtero em anteversão, medindo 5,4 x 2,0 x 3,8 cm.\nEndométrio medindo 0,2 cm de espessura.\nMiométrio com ecogenicidade e ecotextura normais.\nOvário direito medindo 0,6 x 1,2 x 1,2 cm, apresentando poucas imagens anecoicas.\nOvário esquerdo medindo 1,2 x 0,9 x 1,0 cm, apresentando poucas imagens anecoicas.\n\nCONCLUSÃO:\n1) Bexiga ecograficamente normal.\n2) Útero de volume normal (22,3 cm³).\n3) O endométrio tem espessura normal para a faixa etária da menopausa.\n4) Ovários ecograficamente normais (o direito com 0,4 cm³ e o esquerdo com 0,6 cm³), ambos praticamente sem folículos.",
  },
  // 4) Menopausa TA-only + ovário não-visualizado + calcificação arqueadas + obs-TA.
  {
    raw: "Ultrassonografia da pelve transabdominal com o útero em anteversão, medindo 5,9 por 2,8 por 3,9, com volume de 34,9. Ovário direito medindo 0,8 por 1,0 por 1,2, com volume de 0,5. Endométrio medindo 0,4. Coloca a frase da classificação das artérias arqueadas. Ovário esquerdo não visualizado. Paciente em menopausa.",
    laudo:
      "ULTRASSONOGRAFIA DA PELVE TRANSABDOMINAL\n\nCOMENTÁRIOS:\nExame realizado com transdutor de 4.0 MHz, pela técnica transabdominal com a bexiga repleta e paciente em decúbito dorsal. Foram realizados múltiplos cortes transversais, longitudinais, oblíquos e coronais, abrangendo toda a pelve. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nBexiga de forma, contorno e ecotextura normais.\nÚtero em anteversão, medindo 5,9 x 2,8 x 3,9 cm.\nEndométrio medindo 0,4 cm de espessura.\nMiométrio com ecogenicidade e ecotextura normais.\nOvário direito medindo 0,8 x 1,0 x 1,2 cm, apresentando poucas imagens anecoicas.\nOvário esquerdo não visualizado.\n\nCONCLUSÃO:\n1) Bexiga ecograficamente normal.\n2) Útero de dimensões normais (volume de 34,9 cm³), apresentando calcificação das artérias arqueadas sem significado patológico.\n3) O endométrio tem espessura normal para a faixa etária da menopausa.\n4) Ovário direito ecograficamente normal (0,5 cm³), praticamente sem folículos.\n5) Ovário esquerdo não visualizado.\n\nObs.: a avaliação do endométrio é limitada pela via transabdominal.",
  },
  // 5) Mioma (FIGO) + O-RADS/anti-líquido-livre (coleção ovariana NÃO vira líquido livre) + istmocele.
  {
    raw: "Ultrassonografia da pelve transabdominal e transvaginal, útero em anteversão medindo 10,1 por 4,9 por 7,2, com volume aumentado de 189,1 cm³. Endométrio medindo 1,1, espessura normal para a fase do ciclo menstrual. Dois miomas, ou seja, imagem com margem regular, o primeiro medindo 2,6 por 1,7 por 2,4 centímetros, situado na parede anterior e lateral direita, com manto interno de 0,4 centímetros, e o segundo medindo 2,7 por 2,4 por 2,5 centímetros, situado na parede anterior e lateral esquerda. Adicione uma istmocele, imagem anecoica com forma triangular medindo 0,8 por 0,5 por 0,9 centímetros, com miométrio residual de 0,5 centímetros e miométrio adjacente de 1,0 centímetros. Ovário esquerdo medindo 3,9 por 2,8 por 3,3 centímetros, apresentando imagem anecoica que mede 3,1 centímetros no seu maior eixo; na conclusão, ovário esquerdo de volume aumentado, o volume é de 19,9 centímetros cúbicos, às custas de pequena coleção líquida provavelmente funcional, entre parênteses O-RADS 2. Ovário direito medindo 2,0 por 1,9 por 1,8, com volume de 3,8.",
    laudo:
      "ULTRASSONOGRAFIA DA PELVE TRANSABDOMINAL E TRANSVAGINAL\n\nCOMENTÁRIOS:\nExame realizado inicialmente com transdutor de 4.0 MHz, pela técnica transabdominal com a bexiga repleta e paciente em decúbito dorsal. Após a micção, foi introduzido transdutor de 6.5 MHz com a finalidade de realizar a técnica transvaginal. Foram realizados múltiplos cortes transversais, longitudinais, oblíquos e coronais, abrangendo toda a pelve. A documentação fotográfica foi obtida em 06 fotos, segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nBexiga de forma, contorno e ecotextura normais.\nÚtero em anteversão, medindo 10,1 x 4,9 x 7,2 cm.\nImagem anecoica no istmo, de forma triangular, medindo 0,8 x 0,5 x 0,9 cm, com miométrio residual de 0,5 cm e miométrio adjacente de 1,0 cm.\nEndométrio medindo 1,1 cm de espessura.\nMiométrio apresentando imagem hipoecoica e heterogênea, com margens regulares, medindo 2,6 x 1,7 x 2,4 cm, situada na parede anterior e lateral direita, com manto interno de 0,4 cm.\nMiométrio apresentando imagem hipoecoica e heterogênea, com margens regulares, medindo 2,7 x 2,4 x 2,5 cm, situada na parede anterior e lateral esquerda.\nOvário direito medindo 2,0 x 1,9 x 1,8 cm, apresentando imagens anecoicas.\nOvário esquerdo medindo 3,9 x 2,8 x 3,3 cm, apresentando imagem anecoica medindo 3,1 cm em seu maior eixo.\n\nCONCLUSÃO:\n1) Bexiga ecograficamente normal.\n2) Útero de volume aumentado (189,1 cm³).\n3) O endométrio tem espessura normal para a fase do ciclo menstrual.\n4) Miométrio apresentando imagem sólida, que tem como diagnóstico mais provável nódulo miomatoso intramural (categoria FIGO 5).\n5) Miométrio apresentando imagem sólida, que tem como diagnóstico mais provável nódulo miomatoso intramural (categoria FIGO 4).\n6) Ovário direito ecograficamente normal (3,8 cm³), contendo folículos.\n7) Ovário esquerdo de volume aumentado (19,9 cm³), às custas de pequena coleção líquida provavelmente funcional (O-RADS 2).\n8) Nicho de cicatriz cesárea, tipo simples.\n\nFIGO: Federação Internacional de Ginecologia e Obstetrícia.",
  },
  // 6) Pós-abortamento — produtos retidos + imagens hiperecoicas amorfas.
  {
    raw: "Ultrassonografia da pelve transabdominal e transvaginal com útero em anteversão medindo 8,9 por 4,3 por 5,2, volume de 105,0. No corpo, substitua a frase do endométrio por: endométrio heterogêneo medindo 1,8 cm de espessura máxima em região ístmico-cervical; e acrescente outra frase: imagens hiperecoicas amorfas na cavidade endometrial. Na conclusão, no lugar da frase do endométrio normal, coloque: pequena quantidade de produtos retidos da concepção. Ovário direito medindo 2,4 por 1,2 por 2,2 com volume de 3,4. Ovário esquerdo medindo 3,1 por 1,9 por 2,2 com volume de 7,2.",
    laudo:
      "ULTRASSONOGRAFIA DA PELVE TRANSABDOMINAL E TRANSVAGINAL\n\nCOMENTÁRIOS:\nExame realizado inicialmente com transdutor de 4.0 MHz, pela técnica transabdominal com a bexiga repleta e paciente em decúbito dorsal. Após a micção, foi introduzido transdutor de 6.5 MHz com a finalidade de realizar a técnica transvaginal. Foram realizados múltiplos cortes transversais, longitudinais, oblíquos e coronais, abrangendo toda a pelve. A documentação fotográfica foi obtida segundo protocolo internacional de Serviços de Imagem, que possuem várias metodologias.\n\nOS SEGUINTES ASPECTOS FORAM OBSERVADOS:\nBexiga de forma, contorno e ecotextura normais.\nÚtero em anteversão, medindo 8,9 x 4,3 x 5,2 cm.\nEndométrio heterogêneo medindo 1,8 cm de espessura máxima em região ístmico-cervical.\nImagens hiperecoicas amorfas na cavidade endometrial.\nMiométrio com ecogenicidade e ecotextura normais.\nOvário direito medindo 2,4 x 1,2 x 2,2 cm, apresentando imagens anecoicas.\nOvário esquerdo medindo 3,1 x 1,9 x 2,2 cm, apresentando imagens anecoicas.\n\nCONCLUSÃO:\n1) Bexiga ecograficamente normal.\n2) Útero de volume normal (105,0 cm³).\n3) Pequena quantidade de produtos retidos da concepção.\n4) Ovários ecograficamente normais (o direito com 3,4 cm³ e o esquerdo 7,2 cm³), ambos contendo folículos.",
  },
];
